platform: "kubernetes"
operator:
  image: ""
oneagent:
  name: "oneagent"
  apiUrl: "https://uip90407.live.dynatrace.com/api"
  image: ""
  args:
    - --set-app-log-content-access=true
  env:
  - name: ONEAGENT_ENABLE_VOLUME_STORAGE
    value: "true"
  nodeSelector: {}
  labels: {}
  skipCertCheck: false
  disableAgentUpdate: false
  enableIstio: false
  dnsPolicy: ""
  resources: {}
  waitReadySeconds: null
  priorityClassName: ""
  serviceAccountName: ""
  proxy: ""
  trustedCAs: ""
secret:
  apiToken: ""
  paasToken: ""
